spring:
  config:
    import:
      - aws-parameterstore:/togetherBuy/common/
      - classpath:application-security-deploy.yml
  cloud:
    aws:
      region:
        static: ${AWS_REGION}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
    gateway:
      mvc:
        routes:
          # 빌링 서비스
          - id: billing_route
            uri: http://billing:8080           # Billing 서비스의 Docker Compose 서비스명
            predicates:
              - Path=/api/billing/**

          # 채팅 서비스
          - id: chat_route
            uri: http://chat:8080
            predicates:
              - Path=/api/chat/**

          # 알림 서비스
          - id: notification_route
            uri: http://notification:8080
            predicates:
              - Path=/api/notification/**

          # 그 외 모든 /api/** 요청 (로그인 요청 포함)는 Main 서비스로 라우팅
          - id: main_route
            uri: http://main:8080
            predicates:
              - Path=/api/**

          - id: oauth2_redirect_route
            uri: http://main:8080
            predicates:
              - Path=/login/oauth2/code/**
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  application:
    name: TogetherBuyGateway

server:
  port: 8080
