spring:
  cloud:
    aws:
      region:
        static: ${AWS_REGION}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}  # 환경변수에서 읽기
        secret-key: ${AWS_SECRET_ACCESS_KEY} # 환경변수에서 읽기

  config:
    import:
      - aws-parameterstore:/togetherBuy/common/

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${social.googleClientId}
            client-secret: ${social.googleClientSecret}
            redirect-uri: "https://togethrebuy.com/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            client-name: Google
            provider: google
          naver:
            client-id: ${social.naver.clientID}
            client-secret: ${social.naver.secret}
            redirect-uri: "https://togethrebuy.com/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

  jwt:
    access-token-secret: ${jwt.accessKey}
    refresh-token-secret: ${jwt.secretKey}
    access-token-expiration: ${jwt.accessExpiration}
    refresh-token-expiration: ${jwt.secretExpiration}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.client: DEBUG